config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'en#index'

  get 'en/aboutme'
  get 'en/feedback'
  get 'en/index'
  get 'en/interpretation'
  get 'en/overview'
  get 'en/translation'
  get 'en/licenses'
  get 'de/ubermich'
  get 'de/allgemeines'
  get 'de/feedback'
  get 'de/ubersetzen'
  get 'de/dolmetschen'
  get 'de/index'
  get 'de/linzenzen'

  get 'en/contact', to: 'messages#new', lang: 'en'
  get 'de/kontakt', to: 'messages#new', lang: 'de'
  post 'messages/create'

  get '/check.txt', to: proc {[200, {}, ['it_works']]}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

require 'mailgun-ruby'

class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :phone_number, :body, :lang
  validates :name, :email, :body, presence: true

  def send
    mg_client = Mailgun::Client.new ENV['mailgun_secret_api_key']
    info = {
      from: email,
      to: 'corneliakelinske@gmail.com',
      subject: "#{name} - corneliakelinske.com",
      text: "From: #{name}\nEmail: #{email}\nPhone: #{phone_number}\nLanguage: #{lang} \n\n #{body}"
    }
    mg_client.send_message 'mg.corneliakelinske.com', info
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/de_controller.rb
class DeController < ApplicationController
  def ubermich; end

  def leistungen; end

  def feedback; end

  def kontakt; end

  def ubersetzen; end

  def dolmetschen; end

  def index; end
end

app/controllers/en_controller.rb
class EnController < ApplicationController
  def aboutme; end

  def contact; end

  def feedback; end

  def index; end

  def interpretation; end

  def resume; end

  def services; end

  def translation; end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  def new
    @message = Message.new
    @lang = params['lang']
  end

  def create
    @message = Message.new message_params
    if verify_recaptcha(model: @message) && @message.valid?
      @message.send
      flash[:success] = if @message.lang == 'de'
                          'Ich habe Ihre Nachricht erhalten und werde mich bald melden!'
                        else
                          'I have received your message and will be in touch soon!'
                        end
      redirect_to root_path
    else
      if @message.lang == 'de'
        flash.now[:warning] = 'Beim Senden Ihrer Nachricht ist ein Fehler aufgetreten. Bitte versuche es erneut.'
      else
        flash.now[:warning] = 'There was an error sending your message. Please try again.'
      end
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :phone_number, :body, :lang)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/de_helper.rb
module DeHelper
end

app/helpers/en_helper.rb
module EnHelper
end

app/views/de/_footer.html.erb
<footer class="footer container-fluid bg-brown4 d-flex justify-content-between border-top border-orange2">
    <%= link_to(de_linzenzen_path, html_options = {class: 'text-footer'}) do %>
        <i class="far fa-question-circle"></i><span class="d-none d-sm-inline-block pl-1"> Linzenzen</span>
    <% end %>
    <%= link_to(de_kontakt_path, html_options = {class: 'text-footer'}) do %>
        <i class="far fa-envelope"></i><span class="d-none d-sm-inline-block pl-1"> Kontakt Cornelia</span>
    <% end %>
    <%= link_to('https://www.alanvardy.com/', html_options = {class: 'text-footer', target: "_blank"}) do %>
        <i class="fas fa-sitemap"></i></i><span class="d-none d-sm-inline-block pl-1"> Webmaster</span>
    <% end %>
</footer>

app/views/de/_navbar.html.erb
<%
change_language =
{
  'Kontakt' => en_contact_path,
  'Über mich' => en_aboutme_path,
  'Feedback' => en_feedback_path,
  'Willkommen' => en_index_path,
  'Dolmetschen' => en_interpretation_path,
  'Übersetzen' => en_translation_path,
  'Allgemeines' => en_overview_path,
  'Linzenzen' => en_licenses_path
}
 %>

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-brown4 border-bottom border-orange2">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav mr-auto">
        <%= link_to 'Home', de_index_path, class: 'nav-item nav-link' %>
        <%= link_to 'Über mich', de_ubermich_path, class: 'nav-item nav-link' %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Leistungen
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Allgemeines', de_allgemeines_path, class: 'dropdown-item' %>
            <%= link_to 'Übersetzen', de_ubersetzen_path, class: 'dropdown-item' %>
            <%= link_to 'Dolmetschen', de_dolmetschen_path, class: 'dropdown-item' %>
          </div>
        </div>
        <%= link_to 'Feedback', de_feedback_path, class: 'nav-item nav-link' %>
        <%= link_to 'Kontakt', de_kontakt_path, class: 'nav-item nav-link' %>

      </div>
      <div class="navbar-nav">
        <%= link_to change_language[yield(:title)], class: 'nav-item nav-link' do%>
        <%= image_tag "canadian.svg", class: "icon d-inline border" %>
        <span class="d-inline">English</span>
        <% end %>

      </div>
    </div>
  </div>
</nav>

app/views/de/allgemeines.html.erb
<% provide(:title, "Allgemeines") %>
<% provide(:lang, "de") %>

<h1></h1>


<h1>
    Allgemeines
</h1>
<div class="row">
    <div class="col-12 col-lg-8 mb-3">
        <p>
            Ich biete Ihnen professionelle <%= link_to 'Übersetzungen', de_ubersetzen_path %> und <%= link_to 'Dolmetschleistungen', de_dolmetschen_path %> zu konkurrenzfähigen Preisen.
            Wie viel für eine Übersetzung oder Dolmetschleistung berechnet wird, hängt von einer Reihe verschiedener
            Faktoren ab. Genauere Informationen hierzu finden Sie, wenn Sie auf die entsprechende Leistung klicken.
            Oder nehmen Sie mit mir <%= link_to 'Kontakt', de_kontakt_path %> auf, um ein unverbindliches und selbstverständlich kostenloses Angebot
            zu erhalten.
        </p>
        <p>
            Qualität steht bei meiner Arbeit an erster Stelle. Ganz gleich welche Art von Projekt Sie mir
            anvertrauen, Folgendes biete ich Ihnen immer:
        </p>
        <p>
            <h2>Qualität aus einer Hand:</h2>
            <ul>
                <li>
                    Ich bin die Person, die Ihr Dokument übersetzt bzw. die Dolmetscherin, mit der Sie arbeiten
                </li>
                <li>
                    Sofern nicht ausdrücklich etwas Gegenteiliges zwischen uns vereinbart wurde, bin ich die einzige Person, die an Ihrem Projekt arbeitet
                </li>
                <li>
                    Fragen, die sich im Laufe des Projekts stellen, können direkt zwischen dem Kunden (Ihnen) und der
                    Übersetzerin (mir) geklärt werden
                </li>
                <li>
                    Ich kann Ihnen das höchste Maß an Zuverlässigkeit bieten: Vereinbarte Abgabetermine werden grundsätzlich eingehalten*
                    </li>
            </ul>
        </p>
        <p>
            <h2>Maßgeschneiderte Leistung:</h2>
            <ul>
                <li>
                    Ihre Projekte sind mir wichtig
                </li>
                <li>
                    Ich sehe mir jede einzelne Anfrage genau an, um einen angemessenen Preis und Abgabetermin vorschlagen zu können
                </li>
                <li>
                    Ihre Präferenzen (z.B. Terminologie, Stil etc.) werden berücksichtigt
                </li>
            </ul>
        </p>
        <p>
            <h2>
                Sie bezahlen für das gewünschte Ergebnis:
            </h2>
        </p>
        <ul>
            <li>Sie bezahlen ausschließlich die Person, die die angeforderten Leistungen erbringt, d.h. mich</li>
            <li>Sie bezahlen keine Dritten für das Management Ihres Übersetzungs-/Dolmetschprojekts</li>
        </ul>

        <small class="text-muted">
            *Es sei denn das Eintreten Höherer Gewalt, einer unerwarteten Krankheit oder ein Unfall halten mich davon
            ab. In solchen, äußerst selten auftretenden Fällen, werde ich Sie unverzüglich informieren und mich,
            falls gewünscht, nach Kräften darum bemühen, für kompetenten Ersatz zu sorgen.
        </small>
    </div>
    <div class="col-12 col-lg-4 mt-3 mb-3">
        <%= image_tag 'edmontonbuildings.jpg', class: 'w-100 d-block rounded shadow mx-auto' %>
    </div>
</div>

app/views/de/dolmetschen.html.erb
<% provide(:title, "Dolmetschen") %>
<% provide(:lang, "de") %>

<h1>Dolmetschen</h1>
<p>
    Einfach gesagt ist Dolmetschen mündliches Übersetzen.
    Mein Leistungsangebot umfasst sowohl Konsekutiv- als auch Simultandolmetschen.
</p>
<p>
    <h2>Konsekutivdolmetschen</h2>
    Beim Konsekutivdolmetschen spricht der Dolmetscher nachdem der Redner seine Rede (bzw. bei längeren Reden einen Redeabschnitt) beendet hat. Mithilfe einer speziellen Notizentechnik kann der Dolmetscher  Reden (bzw. Redeabschnitte) von bis zu 10 Minuten konsekutiv verdolmetschen.
    Konsekutivdolmetschen kommt bevorzugt bei bilingualen Veranstaltungen zum Einsatz. Diese Dolmetschart ist ideal für kürzere Reden (z.B. Tischreden) und in bilateralen Konstellationen, in denen der Dolmetscher für beide Seiten dolmetscht, z.B. bei Verhandlungen.
</p>
<p>
    Persönlich habe ich unter anderem in folgenden Situationen konsekutiv gedolmetscht:
    <ul>
        <li>Schlichtungsverhandlung</li>
        <li>Geschäftsverhandlungen</li>
        <li>Reden von hochrangigen Offizieren</li>
        <li>Ausbildungskurse (darunter verschiedene Panzerausbildungskurse, bei denen ich sogar auf dem Panzer gedolmetscht habe)</li>
        <li>Begleitung von ausländischen Delegationen</li>
        <li>Prüfungen</li>
    </ul>
</p>

<em>Hinweis: Gerne stehe ich Ihnen in Alberta auch bei Handwerksprüfungen wie dem Red Seal oder Journeyman Exam zur Seite.</em>
<p>
    <h2>Simultandolmetschen</h2>
    Beim Simultandolmetschen beginnt der Dolmetscher die Verdolmetschung während der Redner spricht. Vom Dolmetscher wird dabei höchste Konzentration gefordert. Daher arbeiten Dolmetscher bei dieser Dolmetschart in der Regel mit mindestens einem anderen Dolmetscher zusammen und sitzen in einer schalldichten Kabine.
</p>
<p>
    Diese Dolmetschart wird bevorzugt bei Konferenzen und anderen internationalen Versammlungen mit einer großen Zahl an Teilnehmern verwendet.
    Eine Sonderform des Simultandolmetschens ist das Flüsterdolmetschen. Hierbei sitzt oder steht der Dolmetscher hinter dem Kunden und, wie der Name schon sagt, flüstert diesem die Verdolmetschung ins Ohr.
    Diese Dolmetschvariante kann nur verwendet werden, wenn nicht mehr als maximal zwei Personen eine Verdolmetschung benötigen. Für diese Form des Simultandolmetschens wird keine Kabine benötigt, jedoch stellt sie eine besondere Belastung für den Dolmetscher dar und die übrigen Zuhörer können sich durch das ständige Flüstern im Hintergrund gestört fühlen.
</p>

Ich habe im Rahmen verschiedener Konferenzen simultan gedolmetscht (mit und ohne Kabine)

Hinweis: Bitte beachten Sie, dass die Dolmetschtechnik von mir nicht zur Verfügung gestellt wird.
<p>
    <h2>Preise</h2>
    Abhängig von der Dauer des Dolmetscheinsatzes, rechne ich entweder in Tages- oder Stundensätzen ab.
    Die Höhe des Satzes wird anhand der folgenden Faktoren bestimmt:
    <ul>
        <li>Dolmetschart (konsekutiv oder simultan)</li>
        <li>Thema und Art der Veranstaltung für die die Verdolmetschung benötigt wird</li>
        <li>Dauer der Veranstaltung</li>
    </ul>
</p>
<p>
    Zusätzliche Kosten wie Parkgebühren, Reisekosten und Kosten für Verpflegung und Unterkunft werden ggf. zusätzlich in Rechnung gestellt.
</p>
<p>
    Bitte nehmen Sie mit mir <%= link_to 'Kontakt', de_kontakt_path %> auf, um ein kostenloses und unverbindliches Angebot zu erhalten.
</p>

app/views/de/index.html.erb
<% provide(:title, "Willkommen") %>
<% provide(:lang, "de") %>

<h1>Herzlich Willkommen!</h1>

<div class="row">
    <div class="col-12 col-lg-6 mb-3">
        <p>
            Sie benötigen professionelle Übersetzungen und Dolmetschleistungen für die Sprachkombinationen Deutsch –
            Englisch und/oder Englisch – Deutsch? Hier sind Sie an der richtigen Adresse.
        </p>
        <p>
            Als Diplom-Dolmetscherin und Übersetzerin mit umfassender Erfahrung in vielen Fachbereichen stelle ich
            Ihnen Sprachdienstleistungen von höchster Qualität zur Verfügung. Genauere Informationen zu meiner
            Qualifikation und Berufserfahrung finden Sie im Bereich <%= link_to 'Über mich', de_ubermich_path %>. Wenn Sie mehr über die angebotenen
            Leistungen erfahren möchten, klicken Sie bitte auf <%= link_to 'Leistungen', de_allgemeines_path %>.
        </p>
        <p>
            Falls Sie Fragen haben oder ein kostenloses, unverbindliches Angebot für eine Übersetzung oder einen
            Dolmetschauftrag erhalten möchten, können Sie sich gerne mit mir in <%= link_to 'Kontakt setzen', de_kontakt_path %>.
        </p>
        <p>
            Ich freue mich auf Ihre Aufträge!
        </p>
    </div>
    <div class="col-12 col-lg-6 mt-3 mb-3">
        <%= image_tag 'cornelia_desk2.jpg', class: 'w-100 d-block rounded shadow mx-auto' %>
    </div>
</div>

<% @feedback = [
    {text:  %(
                Sie dürfen mit einer ausgezeichneten Übersetzung rechnen.
            ),
    author: ["Julia Glaremin","Geschäftsführende Gesellschafterin","Apollo Lingua GbR"]},

] %>

<%= render 'layouts/feedback', center: true %>

app/views/de/ubersetzen.html.erb
<% provide(:title, "Übersetzen") %>
<% provide(:lang, "de") %>

<h1>Übersetzen</h1>
<p>
    Als professionelle Übersetzerin betrachte ich Ihren Text immer als Ganzes.
    Das bedeutet, dass ich den Kontext, Stil und die Leser, an die der Text sich richtet, stets im Blick habe.
    Auf diese Weise wird sichergestellt, dass die fertige Übersetzung nicht eine bloße Ansammlung von einzeln
    übersetzten Worten ist, sondern ein in sich schlüssiger Text, der sich nicht liest wie eine Übersetzung
    und der an ihre Anforderungen und ihren Adressatenkreis angepasst ist.
</p>
<p>
    <h2>Fachgebiete</h2>
    <p>
        Im Laufe der Jahre habe ich Übersetzungserfahrung in vielen Fachgebieten sammeln können.
        Die Bereiche, auf die ich mich mittlerweile hauptsächlich spezialisiert habe sind:
    </p>
    <ul>
        <li>Recht (z.B. Abkommen, Verträge, Klageschriften [vor allem im Bereich Patentrecht])</li>
        <li>Technik (z.B. Benutzerhandbücher, Patentschriften)</li>
        <li>Militär (von Beschaffungsverträgen bis hin zu Operationsbefehlen)</li>
        <li>Marketing (Webseitenbeiträge, Newsletter, Werbung)</li>
    </ul>
</p>
<p>
    Darüber hinaus habe ich auch einige eher außergewöhnliche Texte übersetzt, darunter ein Tourprogramm für
    einen Chor, einschließlich der Liedtexte, und ein Buch über die Offenbarung des Johannes.
</p>
<p>
    Gerne arbeite ich mich auch in neue Themenbereiche ein.
</p>
<p>
    <h2>Preise</h2>
    Grundsätzlich rechne ich Übersetzungen pro Wort ab (bei Word-Dokumenten ist die Wortzahl des Ausgangstextes
    ausschlaggebend, bei PDFs die Wortzahl des Zieltextes)
    Welcher Satz berechnet wird, ist von den folgenden Faktoren abhängig:
    <ul>
        <li>Wortzahl</li>
        <li>Textart</li>
        <li>Anforderungen an die Formatierung</li>
        <li>Abgabetermin</li>
    </ul>
</p>

<p>
    Bitte <%= link_to 'kontaktieren', de_kontakt_path %> Sie mich, um ein kostenloses, unverbindliches Angebot zu
    erhalten. Selbstverständlich werden all Ihre Daten und Dokumente vertraulich behandelt.
</p>

<p>
    <h2>Beglaubigte Übersetzungen</h2>
    In beiden Sprachrichtungen (Englisch – Deutsch und Deutsch – Englisch) biete ich (für Kanada)  beglaubigte Übersetzungen an.
</p>

app/views/en/_footer.html.erb
<footer class="footer container-fluid bg-brown4 d-flex justify-content-between border-top border-orange2">
    <%= link_to(en_licenses_path, html_options = {class: 'text-footer'}) do %>
        <i class="far fa-question-circle"></i><span class="d-none d-sm-inline-block pl-1"> Licences</span>
    <% end %>
    <%= link_to(en_contact_path, html_options = {class: 'text-footer'}) do %>
        <i class="far fa-envelope"></i><span class="d-none d-sm-inline-block pl-1"> Contact Cornelia</span>
    <% end %>
    <%= link_to('https://www.alanvardy.com/', html_options = {class: 'text-footer', target: "_blank"}) do %>
        <i class="fas fa-sitemap"></i></i><span class="d-none d-sm-inline-block pl-1"> Webmaster</span>
    <% end %>
</footer>

app/views/en/_navbar.html.erb
<%
change_language =
{
  'Contact Me' => de_kontakt_path,
  'About Me' => de_ubermich_path,
  'Feedback' => de_feedback_path,
  'Welcome' => de_index_path,
  'Interpretation' => de_dolmetschen_path,
  'Translation' => de_ubersetzen_path,
  'Overview' => de_allgemeines_path,
  'Licenses' => de_linzenzen_path
}
 %>

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-brown4 border-bottom border-orange2">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav mr-auto">
        <%= link_to 'Home', en_index_path, class: 'nav-item nav-link' %>
        <%= link_to 'About Me', en_aboutme_path, class: 'nav-item nav-link' %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Services
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Overview', en_overview_path, class: 'dropdown-item' %>
            <%= link_to 'Translation', en_translation_path, class: 'dropdown-item' %>
            <%= link_to 'Interpretation', en_interpretation_path, class: 'dropdown-item' %>
          </div>
        </div>
        <%= link_to 'Feedback', en_feedback_path, class: 'nav-item nav-link' %>
        <%= link_to 'Contact', en_contact_path, class: 'nav-item nav-link' %>
      </div>
      <div class="navbar-nav">
        <%= link_to change_language[yield(:title)], class: 'nav-item nav-link' do%>
        <%= image_tag "german.svg", class: "icon d-inline border" %>
        <span class="d-inline">Deutsch</span>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/en/index.html.erb
<% provide(:title, "Welcome") %>
<% provide(:lang, "en") %>
<h1>
    Welcome
</h1>
<div class="row">
    <div class="col-12 col-lg-6 mb-3">
        <p>
            If you are looking for quality translation services from English into German or German into English,
            you are looking in the right place. I am a highly professional language service provider with over a
            decade of experience under my belt.
        </p>
        <p>
            Please see <%= link_to 'About Me', en_aboutme_path %> for more information about my
            qualifications and professional experience. Information about my services and areas of expertise
            is available under <%= link_to 'Services', en_overview_path %>.
        </p>
        <p>
            Feel free to <%= link_to 'contact me', en_contact_path %> if you have any questions or if you would
            like to receive a free and non-binding quote.
        </p>
        <p>
            I am looking forward to working with you!
        </p>
    </div>
    <div class="col-12 col-lg-6 mt-3 mb-3">
        <%= image_tag 'cornelia_desk2.jpg', class: 'w-100 d-block rounded shadow mx-auto' %>
    </div>
</div>
<% @feedback = [
    {text:  %(
                You can expect nothing but
                excellence from her.
            ),
    author: ["Julia Glaremin","Managing Partner"],
    company: ["Apollo Lingua GbR"],
    website: 'http://www.apollo-lingua.com/index.html'}
] %>

<%= render 'layouts/feedback', center: true %>

app/views/en/interpretation.html.erb
<% provide(:title, "Interpretation") %>
<% provide(:lang, "en") %>

<h1>
    Interpretation
</h1>
<p>
    In simple terms, interpretation is the oral translation of spoken words.
    I provide both consecutive and simultaneous interpretation services.
</p>
<h2>
    Consecutive interpreting
</h2>
<p>
    Consecutive interpreting means that the interpreter speaks after the original speaker has finished his/her speech
    (or,
    in the case of longer speeches, a part of the speech). A special note-taking technique allows the interpreter to
    interpret speeches (or parts of speeches) of up to 10 minutes consecutively.
    This type of interpreting is typically used in bilingual settings. It is ideal for shorter speeches (e.g. toasts,
    after-diner speeches) and bilateral settings where the interpreter interprets s for both sides, e.g. arbitration,
    mediation or business negotiations.
</p>
<p>
    Examples of situations where I provided consecutive interpretation services include:
    <ul>
        <li>
            Arbitration
        </li>
        <li>
            Business negotiations
        </li>
        <li>
            Speeches by high-ranking military officers
        </li>
        <li>
            Training courses (including various tank operating courses where I actually interpreted while standing on a
            tank)
        </li>
        <li>
            Visits of foreign delegations
        </li>
        <li>
            Exams
        </li>
    </ul>
</p>
<p>
    Please note: I also provide interpreting/on-site translation services for trade exams such as red seal or
    journeyman
    exams.
</p>
<h2>
    Simultaneous interpreting
</h2>
<p>
    Simultaneous interpreting means that the interpreter speaks at the same time as the original speaker. As this
    requires
    a lot of concentration and effort on the part of the interpreter, simultaneous interpreters usually work in teams
    of
    two or more and sit in a soundproof booth.
</p>
<p>
    This type of interpreting is typically used for conferences, conventions and other types of international meetings
    with
    a large number of participants.
    A special form of simultaneous interpreting is the so-called chuchotage (whisper interpreting) where the
    interpreter
    sits/stands behind his/her client and whispers the speech in the target language into the client’s ear.
    This type of interpreting can be used if no more than two people require interpretation into the specific language.
    No
    technical equipment is required for chuchotage, however, it is extremely hard on the interpreter and might also
    disturb
    other members of the audience.
</p>
<p>
    I have provided simultaneous interpretation/chuchotage for a number of conferences.
</p>
<p>
    Please note: I do not provide interpreting equipment.
</p>
<h2>
    Prices
</h2>
<p>
    Depending on the length and nature of the individual assignment, I will charge on a daily or hourly rate.
    The rate will be determined on the basis of the following factors:

    <ul>
        <li>
            Type of interpreting (consecutive or simultaneous)
        </li>
        <li>
            Subject matter and type of the event for which interpretation is required
        </li>
        <li>
            Duration of the event
        </li>
    </ul>
</p>
<p>
    Additional costs such as parking fees, costs for transportation, accommodation and food will be charged separately.
</p>
<p>
    Please <%= link_to 'contact me', en_contact_path %> to obtain a free and non-binding quote.
</p>

app/views/en/overview.html.erb
<% provide(:title, "Overview") %>
<% provide(:lang, "en") %>

<h1>
    Overview
</h1>
<div class="row">
    <div class="col-12 col-lg-8 mb-3">
        <p>
            I offer professional <%= link_to 'translation', en_translation_path %> and <%= link_to 'interpretation', en_interpretation_path %> services
            at a competitive rate. Prices depend on a number of different factors. Please find out more by clicking on the service you
            require or <%= link_to 'contact me', en_contact_path %> to obtain a free and non-binding quote.
        </p>
        <p>
            I take great pride in my work so you can be assured that providing quality services is always my priority.
        </p>
        <p>
            Irrespective of what kind of project you entrust me with, this is what I offer:
        </p>
        <p>
            <h2>
                Quality from one source:
            </h2>
            <ul>
                <li>
                    I am the person translating your document or the interpreter you will be working with
                </li>
                <li>
                    Unless explicitly agreed otherwise, I am the only person working on your project
                </li>
                <li>
                    Any questions that arise during the project can be clarified directly between the client (you) and the
                    translator/interpreter (me)
                </li>
                <li>
                    I can provide a high level of reliability: Deadlines agreed on will be met.*
                </li>
            </ul>
        </p>
        <p>
            <h2>
                Individual treatment for all projects:
            </h2>
            <ul>
                <li>
                    Your projects are important to me
                </li>
                <li>
                    Each project will be assessed individually to determine appropriate rates and deadlines
                </li>
                <li>
                    Your preferences (e.g. terminology, style etc.) will be respected
                </li>
            </ul>
        </p>
        <p>
            <h2>
                You pay for your desired outcome:
            </h2>
            <ul>
                <li>
                    You only pay the person performing the service you requested, i.e. me
                </li>
                <li>
                    There is no additional cost component paid to third parties for the management of your project
                </li>
            </ul>
        </p>

        <small class="text-muted">
            *Unless a force majeure, sudden illness or accident occurs, in which case I will notify you and make best efforts to
            find a replacement
        </small>
    </div>
    <div class="col-12 col-lg-4 mt-3 mb-3">
        <%= image_tag 'edmontonbuildings.jpg', class: 'w-100 d-block rounded shadow mx-auto' %>
    </div>
</div>